controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_rear_wheel_joint"]
    right_wheel_names: ["right_rear_wheel_joint"]

    wheel_separation: 0.36
    wheel_radius: 0.10

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    use_stamped_vel: false

    base_frame_id: base_link
    odom_frame_id: odom

    # subscribe to /cmd_vel topic
    cmd_vel_topic: /cmd_vel
