controller_manager:
  ros__parameters:
    update_rate: 50

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_rear_wheel_joint"]
    right_wheel_names: ["right_rear_wheel_joint"]
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    enable_odom_tf: true
